{{ if .Values.schema.enabled }}
{{ range .Values.schema.containers }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Values.appName }}-{{ . }}-load
spec:
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: {{ $.Values.appName }}-{{ . }}-load
        image: 897722697588.dkr.ecr.us-east-1.amazonaws.com/roboshop-schema-load:latest
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: true
        env:
          - name: SCHEMA_FILE
            value: db/{{ . }}.{{ $.Values.schema.dbExtention }}
        envFrom:
        - secretRef:
            name: {{ $.Values.appName }}-job
      restartPolicy: Never
{{ end }}
{{ end }}

